security:
    # 1. Configuración del sistema de cifrado
    password_hashers:
        App\Entity\User: 'bcrypt'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'

    # NUEVO: Jerarquía de Roles
    # Esto hace que el ADMIN herede automáticamente los permisos de los demás
    role_hierarchy:
        ROLE_CONTABILIDAD: ROLE_USER
        ROLE_TECNOLOGIA:   ROLE_USER
        ROLE_ADMIN:       [ROLE_CONTABILIDAD, ROLE_TECNOLOGIA, ROLE_USER]

    # 2. Configuración del proveedor de usuarios
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3. Configuración del Firewall
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator

            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    # 4. Control de acceso por roles (MODIFICADO)
    access_control:
        # Permitimos que Contabilidad, Tecnología y Admin entren al panel
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_CONTABILIDAD, ROLE_TECNOLOGIA] }

# Configuración específica para entornos de prueba
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: bcrypt
                cost: 4
